### ISSUE TITLE
Feature Request: Default arguments

### ISSUE THREAD

**Issue by Teajey** [willemt/typed-graphql#4]
GraphQL supports default arguments, which could be extracted from Python syntax: https://graphql.com/learn/arguments/#using-default-values

E.g. this resolver signature
```py
    @staticresolver
    async def list_users(
        data,
        info: GraphQLResolveInfo,
        limit: int = 20,
        reverse: bool = false,
        name_starts_with: str = "",
        last_login_after: Optional[UtcDatetime] = None,
    ) -> UserItems:
        ...
```
Could be reflected in the GraphQL schema as
```gql
  listUsers(
    limit: Int! = 20
    reverse: Boolean! = false
    nameStartsWith: String! = ""
    lastLoginAfter: String = null
  ): UserItems!
```
Which makes the schema more informative.

It's also nice because you don't always want an optional argument to be `None`able, particularly if `None` doesn't have a specific meaning as a possible argument. For instance, the difference between `listUsers(reverse: false)` and `listUsers(reverse: null)` is ambiguous. The latter possibility only introduces extra complexity, and an opportunity for a bug to slip in

**Comment by willemt** [comment]
thanks for the great suggestion!
added in ee3917a
released in `0.39.0`
